version: 2
jobs:
  ci:
    docker:
       - image: circleci/ruby:2.4.1-node-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: build gem
          command: gem build devicefarm.gemspec
  cd:
    docker:
       - image: circleci/ruby:2.4.1-node-browsers

    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install credentials
          command: gem build devicefarm.gemspec
      - run:
          name: publish gem
          command: |
            mkdir ~/.gem
            ruby deploy.rb

workflows:
  version: 2
  ci-cd:
    jobs:
      - ci
      - cd:
          requires:
            - ci
          filters:
            branches:
              only:
                - /master*/